name: OpenVEX

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  openvex:
    name: OpenVEX

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install vexctl
        uses: openvex/setup-vexctl@main
        with:
          vexctl-release: "0.4.4"

      - name: Verify installation
        run: vexctl version