name: OpenVEX

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  openvex:
    name: OpenVEX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install vexctl
        run: |
          curl --fail --location --silent --show-error \
            --output vexctl \
            https://github.com/openvex/vexctl/releases/download/v0.4.4/vexctl-linux-amd64

          chmod +x vexctl
          sudo mv vexctl /usr/local/bin/vexctl

      - name: Verify installation
        run: vexctl version