name: OpenVEX

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  openvex:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install vexctl
        run: |
          curl -sSfL \
            https://github.com/openvex/vexctl/releases/latest/download/vexctl_linux_amd64.tar.gz \
            | tar xz
          
          sudo mv vexctl /usr/local/bin/